#!/usr/bin/env python3
"""
Validate web-report JSON against the required format.

This script validates the JSON report generated by WEB-SYNTHESIZER
to ensure it conforms to all format requirements.

Usage:
    python validate-web-report.py reports/web-report-2025-12-18-abc1234.json

Exit codes:
    0 - Validation passed
    1 - Validation failed
"""

import argparse
import json
import sys
from pathlib import Path


# =============================================================================
# ALLOWED VALUES (ENUMS)
# =============================================================================

ALLOWED_VERDICTS = {"APPROVE", "REVIEW", "CAREFUL", "REJECT"}
ALLOWED_SEVERITIES = {"Blocker", "Critical", "Major", "Medium", "Minor", "Info"}
ALLOWED_CATEGORIES = {"Security", "Reliability", "Maintainability"}
ALLOWED_SOURCES = {"analyzer", "security", "reviewer", "sonarqube"}
ALLOWED_STATUSES = {"pending"}


# =============================================================================
# VALIDATION FUNCTIONS
# =============================================================================

def validate_structure(data: dict) -> list[str]:
    """Validate top-level structure."""
    errors = []

    # Check required top-level keys
    required_keys = {"metadata", "issues", "issueDetails"}
    missing = required_keys - set(data.keys())
    if missing:
        errors.append(f"Missing top-level keys: {missing}")

    return errors


def validate_metadata(metadata: dict) -> list[str]:
    """Validate metadata section."""
    errors = []

    if not isinstance(metadata, dict):
        return ["metadata is not an object"]

    # Check required fields
    required_fields = {"commit", "branch", "timestamp", "verdict", "score"}
    missing = required_fields - set(metadata.keys())
    if missing:
        errors.append(f"metadata missing fields: {missing}")

    # Validate verdict
    verdict = metadata.get("verdict")
    if verdict and verdict not in ALLOWED_VERDICTS:
        errors.append(f"Invalid verdict '{verdict}'. Allowed: {ALLOWED_VERDICTS}")

    # Validate score
    score = metadata.get("score")
    if score is not None:
        if not isinstance(score, (int, float)):
            errors.append(f"score must be a number, got {type(score).__name__}")
        elif not (0 <= score <= 100):
            errors.append(f"score must be between 0 and 100, got {score}")

    return errors


def validate_issue(issue: dict, index: int) -> list[str]:
    """Validate a single issue."""
    errors = []
    prefix = f"issues[{index}]"

    if not isinstance(issue, dict):
        return [f"{prefix} is not an object"]

    # Check required fields
    required_fields = {"id", "source", "title", "category", "severity", "isBug", "file", "line", "status"}
    missing = required_fields - set(issue.keys())
    if missing:
        errors.append(f"{prefix} missing fields: {missing}")

    issue_id = issue.get("id", f"issue_{index}")

    # Validate source (must be array)
    source = issue.get("source")
    if source is not None:
        if not isinstance(source, list):
            errors.append(f"{prefix} ({issue_id}): 'source' must be an array, got {type(source).__name__}")
        else:
            for src in source:
                if src not in ALLOWED_SOURCES:
                    errors.append(f"{prefix} ({issue_id}): Invalid source '{src}'. Allowed: {ALLOWED_SOURCES}")

    # Validate severity
    severity = issue.get("severity")
    if severity and severity not in ALLOWED_SEVERITIES:
        errors.append(f"{prefix} ({issue_id}): Invalid severity '{severity}'. Allowed: {ALLOWED_SEVERITIES}")

    # Validate category
    category = issue.get("category")
    if category and category not in ALLOWED_CATEGORIES:
        errors.append(f"{prefix} ({issue_id}): Invalid category '{category}'. Allowed: {ALLOWED_CATEGORIES}")

    # Validate isBug (must be boolean)
    is_bug = issue.get("isBug")
    if is_bug is not None and not isinstance(is_bug, bool):
        errors.append(f"{prefix} ({issue_id}): 'isBug' must be boolean, got {type(is_bug).__name__}")

    # Validate status
    status = issue.get("status")
    if status and status not in ALLOWED_STATUSES:
        errors.append(f"{prefix} ({issue_id}): Invalid status '{status}'. Allowed: {ALLOWED_STATUSES}")

    # Validate line (must be integer)
    line = issue.get("line")
    if line is not None and not isinstance(line, int):
        errors.append(f"{prefix} ({issue_id}): 'line' must be integer, got {type(line).__name__}")

    return errors


def validate_issue_details(issue_details: dict, issue_id: str) -> list[str]:
    """Validate issue details for a single issue."""
    errors = []
    prefix = f"issueDetails[{issue_id}]"

    if not isinstance(issue_details, dict):
        return [f"{prefix} is not an object"]

    # Check required fields
    required_fields = {"where", "why", "how"}
    missing = required_fields - set(issue_details.keys())
    if missing:
        errors.append(f"{prefix} missing fields: {missing}")

    # Validate 'where' contains code snippet
    where = issue_details.get("where", "")
    if where:
        if "```" not in where:
            errors.append(f"{prefix}.where: Missing code snippet (no ``` found)")
        if len(where) < 150:
            errors.append(f"{prefix}.where: Too short ({len(where)} chars < 150 minimum)")
    else:
        errors.append(f"{prefix}.where: Empty or missing")

    # Validate 'why' contains mermaid diagram
    why = issue_details.get("why", "")
    if why:
        if "```mermaid" not in why:
            errors.append(f"{prefix}.why: Missing Mermaid diagram (no ```mermaid found)")
        if len(why) < 200:
            errors.append(f"{prefix}.why: Too short ({len(why)} chars < 200 minimum)")
    else:
        errors.append(f"{prefix}.why: Empty or missing")

    # Validate 'how' is not empty
    how = issue_details.get("how", "")
    if how:
        if len(how) < 200:
            errors.append(f"{prefix}.how: Too short ({len(how)} chars < 200 minimum)")
    else:
        errors.append(f"{prefix}.how: Empty or missing")

    return errors


def validate_issues_details_match(issues: list, issue_details: dict) -> list[str]:
    """Validate that issues and issueDetails match."""
    errors = []

    issues_count = len(issues)
    details_count = len(issue_details)

    if issues_count != details_count:
        errors.append(f"CRITICAL: issues.length ({issues_count}) !== Object.keys(issueDetails).length ({details_count})")

    # Check each issue has corresponding details
    for i, issue in enumerate(issues):
        issue_id = issue.get("id")
        if issue_id and issue_id not in issue_details:
            errors.append(f"Issue {issue_id} has no entry in issueDetails")

    # Check for orphan details (details without corresponding issue)
    issue_ids = {issue.get("id") for issue in issues}
    for detail_id in issue_details.keys():
        if detail_id not in issue_ids:
            errors.append(f"issueDetails[{detail_id}] has no corresponding issue")

    return errors


def validate_report(data: dict) -> list[str]:
    """Validate the entire report."""
    all_errors = []

    # 1. Validate structure
    all_errors.extend(validate_structure(data))
    if all_errors:
        return all_errors  # Can't continue if structure is wrong

    # 2. Validate metadata
    all_errors.extend(validate_metadata(data.get("metadata", {})))

    # 3. Validate issues
    issues = data.get("issues", [])
    if not isinstance(issues, list):
        all_errors.append("'issues' must be an array")
    else:
        for i, issue in enumerate(issues):
            all_errors.extend(validate_issue(issue, i))

    # 4. Validate issueDetails
    issue_details = data.get("issueDetails", {})
    if not isinstance(issue_details, dict):
        all_errors.append("'issueDetails' must be an object")
    else:
        for issue_id, details in issue_details.items():
            all_errors.extend(validate_issue_details(details, issue_id))

    # 5. Validate issues/issueDetails match
    if isinstance(issues, list) and isinstance(issue_details, dict):
        all_errors.extend(validate_issues_details_match(issues, issue_details))

    return all_errors


# =============================================================================
# MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Validate web-report JSON format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Exit codes:
    0 - Validation passed
    1 - Validation failed

Example:
    python validate-web-report.py reports/web-report-2025-12-18-abc1234.json
        """
    )

    parser.add_argument(
        "input",
        type=str,
        help="Path to web-report JSON file"
    )

    parser.add_argument(
        "--quiet", "-q",
        action="store_true",
        help="Only output errors, no success message"
    )

    args = parser.parse_args()

    # Validate input file exists
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: File not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    # Load JSON
    try:
        with open(input_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON: {e}", file=sys.stderr)
        sys.exit(1)

    # Validate
    errors = validate_report(data)

    # Output results
    if errors:
        print(f"Validation FAILED for {input_path}", file=sys.stderr)
        print(f"Found {len(errors)} error(s):", file=sys.stderr)
        print("", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        print("", file=sys.stderr)
        sys.exit(1)
    else:
        if not args.quiet:
            issues_count = len(data.get("issues", []))
            details_count = len(data.get("issueDetails", {}))
            verdict = data.get("metadata", {}).get("verdict", "N/A")
            score = data.get("metadata", {}).get("score", "N/A")

            print(f"Validation PASSED for {input_path}")
            print(f"  - Issues: {issues_count}")
            print(f"  - IssueDetails: {details_count}")
            print(f"  - Verdict: {verdict}")
            print(f"  - Score: {score}")
        sys.exit(0)


if __name__ == "__main__":
    main()
